
tasks:
  provision:
    action: !provision
      output: ${taskOutputDir}/provisionResult.txt
      graalVmVersion: ${pluginSettings.version}
      graalVmDistribution: ${pluginSettings.distribution}
      acknowledgeLicense: ${pluginSettings.acknowledgeOracleLicense}

  buildNativeImage:
    action: !buildNativeImage
      graalVmHomePath: ${provision.taskOutputDir}/provisionResult.txt
      jarPath: ${module.jar}
      classpath: ${module.runtimeClasspath}
      mainClass: ${pluginSettings.mainClass}
      output: ${taskOutputDir}/nativeImage
