
tasks:
  provision:
    action: !provision
      output: ${taskOutputDir}/provisionResult.txt
      graalVmVersion: ${pluginSettings.version}
      graalVmDistribution: ${pluginSettings.distribution}
      acknowledgeLicense: ${pluginSettings.acknowledgeOracleLicense}

  buildNativeImage:
    action: !buildNativeImage
      graalVmHomePath: ${provision.action.output}
      classpath: ${module.runtimeClasspath}
      mainClass: ${pluginSettings.mainClass}
      output: ${taskOutputDir}/nativeImage

  runTracingAgent:
    action: !tracingAgent
      resources: ${module.resources}
      classpath: ${module.runtimeClasspath}
      graalVmHomePath: ${provision.action.output}
      mainClass: ${pluginSettings.mainClass}
